---
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: 
        - "--markdown-linebreak-ext=md"
      exclude: "*.md"
    - id: check-yaml
      args:
        - "--allow-multiple-documents"
      exclude: "templates/*"
    - id: check-json
    - id: check-symlinks
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args:
        - "--fix=lf"
    
    # Security
    - id: detect-private-key

# Terraform Hooks
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
      args:
        - "--args=--config=.terraform-docs.yaml"
        - "--args=--lockfile=false"
    - id: terraform_providers_lock
    - id: terraform_tflint
      exclude: "examples/*"
      args:
        - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"

# Shell Script Formatter and Markdown Linter
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shfmt
      args:
        - "'-l', '-i', '2', '-ci', '-sr', '-w'"
    - id: markdownlint

# JSON5 Linter
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0-alpha.4
  hooks:
  - id: prettier
    files: '.json5$'