name: 'run-pre-commit-hooks'
# This workflow runs the pre-commit hooks defined in .pre-commit-config.yaml

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    env:
      TF_IN_AUTOMATION: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout from Github
      uses: actions/checkout@v3
    - name: Setup Python3
      uses: actions/setup-python@v3
    - name: Install TfLint
      uses: terraform-linters/setup-tflint@v3
    - name: Run Terraform-docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        config-file: .terraform-docs.yaml
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
    - uses: pre-commit/action@v3.0.0
